version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:8000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        $$_SERVER['REQUEST_URI'] = str_replace("/wp-admin/", "/wordpress/wp-admin/",  $$_SERVER['REQUEST_URI']);
        define( 'WP_HOME', 'https://up4soft.test/wordpress' );
        define( 'WP_SITEURL', 'https://up4soft.test/wordpress' );
    volumes:
      - wordpress:/var/www/html
      - ./ports.conf:/etc/apache2/ports.conf
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      itnet:
        ipv4_address: 192.168.100.2

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

    networks:
      itnet:
        ipv4_address: 192.168.100.3

  nginx:
    image: nginx:latest
    restart: always  
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
      - ./site/index.html:/var/www/site/index.html
    networks:
      itnet:
        ipv4_address: 192.168.100.4
    depends_on:
      - wordpress

volumes:
  wordpress:
  db:


networks:
  itnet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/28